name: Code Check
on:
  push:
    branches:
      - gh-pages
      - main
      - code-check-action
  pull_request: []
  workflow_dispatch:
jobs:
  code-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests tensorflow seaborn scikit-learn pandas

      - name: Install Code Checker
        run: |
          python3 -m pip install --upgrade git+https://github.com/bpmweel/cce.git#egg=cce

      - name: Checkout the lesson
        uses: actions/checkout@v2

      - name: Download prerequisite files
        run: |
          wget -O weather_prediction_dataset.csv https://zenodo.org/record/4980359/files/weather_prediction_dataset.csv?download=1
          wget -O weather_prediction_bbq_labels.csv https://zenodo.org/record/4980359/files/weather_prediction_bbq_labels.csv?download=1

      - name: Run code checker
        run: |
          ls -l
          pwd
          ls -l _episodes/
          FILES="_episodes/*"
          for f in $FILES
          do
            echo "Checking $f"
            cce -f "$f"
          done
        shell: bash {0} # opt out of fail-fast
