name: Code Check
on:
  push:
    branches:
      - gh-pages
      - main
      - code-check-action
  pull_request: []
jobs:
  code-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests tensorflow seaborn scikit-learn pandas

      - name: Get Code Checker
        run: |
          git clone https://github.com/bpmweel/cce.git

      - name: Install Code Checker
        run: |
          python3 -m pip install --upgrade .
        working-directory: ${{ github.workspace }}/cce

      - name: Run code checkeer
        run: |
          cce -f _episodes/02-keras.md
        working-directory: ${{ github.workspace }}
