name: Code Check
on:
  push:
    branches:
      - gh-pages
      - main
      - code-check-action
  pull_request: []
jobs:
  code-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests tensorflow seaborn scikit-learn pandas

      - name: Install Code Checker
        run: |
          python3 -m pip install --upgrade git+https://github.com/bpmweel/cce.git#egg=cce

      - name: Run code checkeer
        run: |
          echo $PWD
          ls -la
          FILES="_episodes/*"
          for f in $FILES
          do
            echo "Checking $f"
            cce -f "$f"
          done
